cluster: sbatch --export=ALL --partition={resources.partition} --nodes=1 --time {resources.time} --ntasks 1 --mem {resources.mem} --cpus-per-task={resources.cpus} --output=/cache/home/js3054/logs/snakemake/slurm-%A_%a.out --error=/cache/home/js3054/logs/snakemake/slurm-%A_%a.err
default-resources: [time=360,mem=4000,cpus=1,partition='genetics_1']
jobs: 1000